Dataset:
  use_pitch_shift: False

  sr: 16000
  dim_mel: 128      # for Hifi-GAN
  length_mel: 128

  hop_size: 160     # for Hifi-GAN
  n_fft: 1024       # for Hifi-GAN
  

Model:
  use_one_hot: True
  use_spec_input: False
  use_spk_linear: False   # If false, you match the dim_spk by 192 (ecapa-tdnn).
  use_train_T: True
  n_emo: 5


  Style_Prior:
    dim_emo: 5
    dim_spk: 192

    CNF:  # FFJORD
      use_train_T: True
      dim_latent: 128
      dims_cnf: "256-256-256-256-256"

    NSF:  # Neural Spline Flow

  Posterior:
    variance_regularization: 0. 

  VAE:
    #=== Encoder Configuration
    n_EncVCBlock: 3

    dim_encoder_hidden: 128
    kernel_size_encoder: 3
    dropout_encoder: 0.

    #=== Decoder Configuration
    n_DecVCBlock: 3
    list_upscale: [2, 1, 1]

    dim_decoder_hidden: 128
    kernel_size_decoder: 3
    dropout_decoder: 0.



  Pretrained:
    HuBERT:
      dense_model_name: "hubert-base-ls960"
      quantizer_name: "kmeans"
      vocab_size: 100





Train:
  wandb_login: True
  mode_unit_discrete: False
  mode_flow_detach: False
  

  save_model_path: "./save_model/"
  save_for_step: 10000

  epoch: 100
  batch_size: 64
  num_workers: 8

  learning_rate: 5.e-4    # best: 5.e-4 & 0.99999 LR STEP
  lr_step: 1.

  beta_LL: 0.0078125
  beta_ent: 0.0078125
  annealing_initial_step: 0
  annealing_end_step: 1
  weight_decay: 0.
  


Result:
  asset_dir_path: "./assets/220320/"
  tsne_save_name: "tsne_speaker.jpg"
  reconMel_save_name: "recon_mel.jpg"