Dataset_Info:
  name: "EmovDB"
  num_speakers: 4
  num_emotions: 5
  sr: 16000 # Hz

Paths:
  root_dataset: "/workspace/MSDegree/data"

  path_dataset: "/EmovDB_Dataset"
  path_save: "/EmovDB_preprocessed"

Preprocess:
  top_db: 20
  length_mel: 128

  hop_size: 160    # for Hifi-GAN
  n_mel: 128    # for Hifi-GAN
  n_fft: 1024   



